### ISSUE TITLE
Allow setting timeout on the ClientSession

### ISSUE THREAD

**Issue by cancan101** [lfparis/airbase#10]
Currently the [default timeout on `ClientSession` per aiohttp is 300 seconds](https://docs.aiohttp.org/en/stable/client_quickstart.html#timeouts), which is incredibly long. While the default can be kept, this should be user changable.

**Comment by lfparis** [comment]
Added this to the latest release. Check it out [here](https://github.com/lfparis/airbase/releases/tag/0.0.1b8).

**Comment by cancan101** [comment]
solved
