### ISSUE TITLE
Remove requirement on `async with Airtable()`

### ISSUE THREAD

**Issue by fmorato** [lfparis/airbase#16]
At the moment, it looks like the only way to make requests to Airtable is to make requests inside an `async with Airtable()` block. That is because the session is open only inside Airtable's `async with`. Thus, a `Table.get_record()` only works within that block. While this works well, it would also be nice to create an instance of Airtable, Base, and Table and be able to reuse it, and that it would keep a session open. I can't even do an `async with Table`, as it inherits from `BaseAirtable`.

A simple solution would be to open and close a session at every request if one is not open. This would at least make the library more flexible to use. Another solution would be that each instance would keep its own session open.

What do you think about this?
Was it a deliberate intention that every request to Airtable needs to be inside the `async with Airtable` block?

**Comment by lfparis** [comment]
See PR #12
