### ISSUE TITLE
Issues with metadata API

### ISSUE THREAD

**Issue by cancan101** [lfparis/airbase#20]
It looks like the [metadata api](https://airtable.com/api/meta) calls no longer work without a special token.

Calls to `get_bases` and `get_tables` are just returning `None` for me.

**Comment by lfparis** [comment]
@cancan101 I'm waiting on the Airtable team to provide a client secret to test the new workflow for non-enterprise accounts

**Comment by cancan101** [comment]
Is it just me, or did this code work at some point in the past without a client secret?

**Comment by lfparis** [comment]
It still works for Airtable Enterprise accounts.
