### ISSUE TITLE
Odd implementation for exponential backoff

### ISSUE THREAD

**Issue by cancan101** [lfparis/airbase#5]
Looking at: https://github.com/lfparis/airbase/blob/d5685ae1606ba87133968f1b97b88f76cedfccfd/airbase/airtable.py#L57
I think you want something like:

```
delay = (count ** 2) * 0.1
```
ie a doubling (multiplicative) increase each iteration.
and then ideally count increments by 1 each iteration to make code more understandable.

Also with the current default settings of retries, you do get a pretty long delay on the function call.

**Comment by lfparis** [comment]
Based on your usage, have you explored other delay intervals when running into 429s or timeouts?
Admittedly, I did put in place a conservative delay..

**Comment by cancan101** [comment]
Not sure what I was thinking above when I wrote the formula as I just re-stated yours. What I meant to write was:
```python
delay = (2 ** count) * k
```
and where `k = 0.1` and then you can change `k` as desired but have count just increment by 1 for readability. Technically can also use a different constant from `2` for the backoff.

**Comment by lfparis** [comment]
Checkout the [simplified version](https://github.com/lfparis/airbase/blob/master/airbase/airtable.py#L43)

**Comment by cancan101** [comment]
yep looks good
